### ISSUE TITLE
Govnokod

### ISSUE THREAD

**Issue by left-try** [ice-wiz-test/schholExample#1]
Govnokod

**Comment by Cheaplifer** [comment]
Sam takoy

**Comment by left-try** [comment]
> Money can't buy you love, but it can buy you waifu

**Comment by left-try** [comment]
- [x] Yes

- [x] No

**Comment by ice-wiz-test** [comment]
What the fuck did you say about me, you little bitch? I'll have you know I graduated top of my class in Tinkoff Generation, and I have been involved in countless Stankevich contests. I am trained in TLing O(1) solutions and I am the top trap in all of Moscow's CP community. You are nothing to me but another task(imposter sussy baka). I will wipe the fuck out of you with 512 MB DP's, the ML's of which you have never seen. You think you can get away with speaking to me like this over the Internet? Think again, fucker. As we speak, I am contacting my secret network of retards all over Russia so you better prepare, maggot. The storm that RE's all of your solutions. You are fucking disqualified, kid. I can be anywhere, anytime and on any Codeforces account. Not only am I extensively trained in dropping the queue in contests, but I also have MikeMirzayanov's full support and I will use it to wipe your miserable ass across the Polygon leaderboard, you little shit. If only you knew how much retribution would your funny little "comment" bring upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.
